export enum WorkflowState {
  MAPPING_PENDING = 'MAPPING_PENDING',
  PATHWAY_CONFIRMATION_PENDING = 'PATHWAY_CONFIRMATION_PENDING',
  PATHWAY_SELECTED = 'PATHWAY_SELECTED',
  ASSESSMENT_READY = 'ASSESSMENT_READY',
  ASSESSMENT_IN_PROGRESS = 'ASSESSMENT_IN_PROGRESS',
  CRITERION_RESOLUTION_REQUIRED = 'CRITERION_RESOLUTION_REQUIRED',
  REMEDIATION_REQUIRED = 'REMEDIATION_REQUIRED',
  SIGNOFF_READY = 'SIGNOFF_READY',
  ASSESSOR_DECISION_PENDING = 'ASSESSOR_DECISION_PENDING',
  FINAL_REPORT_READY = 'FINAL_REPORT_READY',
  SIGNED_OFF = 'SIGNED_OFF',
  REPORT_FINALIZED_NOT_RECOMMENDED = 'REPORT_FINALIZED_NOT_RECOMMENDED',
  LOCKED = 'LOCKED'
}

export enum RecommendationOutcome {
  PATHWAY_CONFIRMATION_REQUIRED = 'PATHWAY_CONFIRMATION_REQUIRED',
  UPSKILLING_REQUIRED = 'UPSKILLING_REQUIRED',
  ASSESSMENT_REQUIRED = 'ASSESSMENT_REQUIRED',
  ASSESSMENT_INCOMPLETE = 'ASSESSMENT_INCOMPLETE',
  ASSESSMENT_REVIEW_REQUIRED = 'ASSESSMENT_REVIEW_REQUIRED',
  NOT_SUITABLE_FOR_SIGNOFF = 'NOT_SUITABLE_FOR_SIGNOFF',
  SUITABLE_FOR_SIGNOFF = 'SUITABLE_FOR_SIGNOFF'
}

export enum AssessorDecision {
  ACCEPT_RECOMMENDATION = 'ACCEPT_RECOMMENDATION',
  PATHWAY_ROUTING_OVERRIDE = 'PATHWAY_ROUTING_OVERRIDE',
  RECOMMENDATION_OVERRIDE_DOWNGRADE = 'RECOMMENDATION_OVERRIDE_DOWNGRADE',
  SECOND_REVIEW_REQUEST = 'SECOND_REVIEW_REQUEST'
}

export enum FinalDisposition {
  UPSKILLING_REFERRAL = 'UPSKILLING_REFERRAL',
  SUITABLE_FOR_SIGNOFF = 'SUITABLE_FOR_SIGNOFF',
  NOT_RECOMMENDED = 'NOT_RECOMMENDED',
  REASSESSMENT_REQUIRED = 'REASSESSMENT_REQUIRED'
}

export enum RPLPathway {
  RPL_A = 'RPL_A',
  RPL_B = 'RPL_B',
  RPL_C = 'RPL_C',
  RPL_D = 'RPL_D'
}

export enum ThresholdOperator {
  GREATER_THAN_OR_EQUAL = '>=',
  GREATER_THAN = '>'
}

export enum EducationLevel {
  NONE = 'NONE',
  PRIMARY = 'PRIMARY',
  FIFTH = '5TH',
  EIGHTH = '8TH',
  TENTH = '10TH',
  TWELFTH = '12TH',
  ITI = 'ITI',
  DIPLOMA = 'DIPLOMA',
  UG = 'UG',
  PG = 'PG',
  OTHER = 'OTHER'
}

export enum EnrolmentStatus {
  NONE = 'NONE',
  UG_PURSUING = 'UG_PURSUING',
  PG_PURSUING = 'PG_PURSUING',
  OTHER = 'OTHER'
}

export enum ApplicantContextSource {
  SELF_DECLARED = 'SELF_DECLARED',
  DOCUMENT_VERIFIED = 'DOCUMENT_VERIFIED',
  ORGANIZER_DATA = 'ORGANIZER_DATA'
}

export enum EvidenceType {
  VIDEO = 'VIDEO',
  IMAGE = 'IMAGE',
  DOCUMENT = 'DOCUMENT',
  NOTE = 'NOTE'
}

export enum LocationStatus {
  AVAILABLE = 'AVAILABLE',
  UNAVAILABLE = 'UNAVAILABLE',
  PERMISSION_DENIED = 'PERMISSION_DENIED'
}

export enum ProctoringStatus {
  VERIFIED = 'VERIFIED',
  FLAGGED = 'FLAGGED',
  UNAVAILABLE = 'UNAVAILABLE'
}

export enum AssessmentComponentType {
  THEORY = 'THEORY',
  PRACTICAL = 'PRACTICAL',
  PROJECT = 'PROJECT',
  VIVA = 'VIVA',
  OTHER = 'OTHER'
}

export enum CriterionStatus {
  NOT_DEMONSTRATED = 'NOT_DEMONSTRATED',
  PARTIAL = 'PARTIAL',
  MEETS_ANCHOR = 'MEETS_ANCHOR',
  DEMONSTRATED = 'DEMONSTRATED'
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED'
}

export enum EvaluationDataType {
  SYNTHETIC_DEMO = 'SYNTHETIC_DEMO',
  ORGANIZER_DATA = 'ORGANIZER_DATA',
  PILOT_STUDY = 'PILOT_STUDY',
  OPERATIONAL = 'OPERATIONAL'
}

export enum DataProvenanceCategory {
  OFFICIAL_VERIFIED_SOURCE = 'OFFICIAL_VERIFIED_SOURCE',
  SYNTHETIC_DEMO_FIXTURE = 'SYNTHETIC_DEMO_FIXTURE',
  ORGANIZER_DATA = 'ORGANIZER_DATA',
  REAL_STUDY_DATA = 'REAL_STUDY_DATA',
  MOCK_AI_OUTPUT = 'MOCK_AI_OUTPUT'
}

export enum LocationSourceType {
  DEMO_FIXTURE = 'DEMO_FIXTURE',
  GPS = 'GPS',
  NETWORK = 'NETWORK',
  MANUAL = 'MANUAL'
}

